// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using ProD;

namespace ProD
{
		public class DungeonPopulator
		{
				// reference to map
				private Map map;

				// variables for population
				private int enemy_frequency;
				private int enemy_variety;
				private int boss_fights;
				private int trap_frquency;
				private int health_frequency;
				private int chest_frequency;

				public DungeonPopulator (Map m)
				{
						map = m;

				}

				public void PopulateEnemies ()
				{
					
				}

				public void PopulateTraps ()
				{
				}

				public void PopulateAesthetics ()
				{
				
				}

				public void SetSpecificProperties (int ef, int ev, int bf, int tf, int cf, int hf)
				{
						enemy_frequency = ef;
						enemy_variety = ev;
						boss_fights = bf;
						trap_frquency = tf;
						chest_frequency = cf;
						health_frequency = hf;
				}

		}
}

